### ISSUE TITLE
No transparency

### ISSUE THREAD

**Issue by JanChodorowski** [Xyr0s1gn/deeold#1]
When dragging and dropping a tab within a window/subwindow there is no transparency of the placeholder.

**Comment by misterklaes** [comment]
> When dragging and dropping a tab within a window/subwindow there is no transparency of the placeholder.

You mean this:
![image](https://user-images.githubusercontent.com/9028087/64549314-ffc41c00-d31f-11e9-8208-ab0b574eeb66.png)

- [X] Tab drag`n`drop transparency

**Comment by JanChodorowski** [comment]
Yes, exactly

**Comment by misterklaes** [comment]
Added.
